<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdmissionCommittee.Domain\AdmissionCommittee.Domain.csproj" />
    <ProjectReference Include="..\AdmissionCommittee.Abstractions\AdmissionCommittee.Abstractions.csproj" />
    <ProjectReference Include="..\AdmissionCommittee.Data.Memory\AdmissionCommittee.Data.Memory.csproj" />
  </ItemGroup>

</Project>